// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1EXv_7x49tTl6u3C2-HIWNh260KzX2Cs',
    appId: '1:638832774123:web:0ac94566edd4196e2e67ae',
    messagingSenderId: '638832774123',
    projectId: 'nook-bc74f',
    authDomain: 'nook-bc74f.firebaseapp.com',
    storageBucket: 'nook-bc74f.firebasestorage.app',
    measurementId: 'G-BT2V0CPHMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnXvD47R8Yhzlx1fcsxxzP9bHybUqnYc',
    appId: '1:638832774123:android:aafb3a4eb8422a132e67ae',
    messagingSenderId: '638832774123',
    projectId: 'nook-bc74f',
    storageBucket: 'nook-bc74f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIQbKZgej3hEwOwJmki-c_aVWD8yzqc2o',
    appId: '1:638832774123:ios:a5cd15541476c9852e67ae',
    messagingSenderId: '638832774123',
    projectId: 'nook-bc74f',
    storageBucket: 'nook-bc74f.firebasestorage.app',
    iosBundleId: 'com.example.nook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIQbKZgej3hEwOwJmki-c_aVWD8yzqc2o',
    appId: '1:638832774123:ios:a5cd15541476c9852e67ae',
    messagingSenderId: '638832774123',
    projectId: 'nook-bc74f',
    storageBucket: 'nook-bc74f.firebasestorage.app',
    iosBundleId: 'com.example.nook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1EXv_7x49tTl6u3C2-HIWNh260KzX2Cs',
    appId: '1:638832774123:web:6457d1fb18c064fd2e67ae',
    messagingSenderId: '638832774123',
    projectId: 'nook-bc74f',
    authDomain: 'nook-bc74f.firebaseapp.com',
    storageBucket: 'nook-bc74f.firebasestorage.app',
    measurementId: 'G-FZYPPZ5GH0',
  );
}
